name: DeployToGitHubPages
env:
  PUBLISH_DIR: 9.0/BlazorWebAssemblyXrefGenerator/bin/Release/net8.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    paths:
      - 9.0/BlazorWebAssemblyXrefGenerator/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4.2.2

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4.1.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
