name: Validate sample apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            90BlazorSampleBlazorWebApp:
              - '9.0/BlazorSample_BlazorWebApp'
            80BlazorSampleBlazorWebApp:
              - '8.0/BlazorSample_BlazorWebApp'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore/build 9.0/BlazorSample_BlazorWebApp
        if: steps.filter.outputs.90BlazorSampleBlazorWebApp == 'true'
        run: dotnet build 9.0/BlazorSample_BlazorWebApp

      - name: Restore/build 8.0/BlazorSample_BlazorWebApp
        if: steps.filter.outputs.80BlazorSampleBlazorWebApp == 'true'
        run: dotnet build 8.0/BlazorSample_BlazorWebApp
